spring:
  application:
    name: hr-payroll

server:
  port: 8101

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 6000000

  ribbon:
    ConnectTimeout: 10000000
    ReadTimeout: 20000000
