server:
  port: ${random.int(5000,5100)}

spring:
  application:
    name: hr-worker
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

eureka:
  instance:
    initial-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
