server:
  port: 8001

spring:
  application:
    name: hr-worker
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect