spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          username: ${GITHUB_USER}
          password: ${GITHUB_PASS}
          default-label: main
          uri: https://github.com/moraismat/ms-coures-config
server:
  port: 8888
